onEvent('recipes', event => {
	const recipes = [
		{INPUT : BLOCKS.ALUMINUM, 		OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 1000}, TEMPERATURE : 660, 	KEY : 'aluminum_block'},
		{INPUT : BLOCKS.COPPER,			OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 1000}, TEMPERATURE : 1080, KEY : 'copper_block'},
		{INPUT : BLOCKS.GOLD, 			OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 1000}, TEMPERATURE : 1060, KEY : 'gold_block'},
		{INPUT : BLOCKS.WROUGHT_IRON, 	OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 1000}, TEMPERATURE : 1536, KEY : 'wrought_iron_block'},
		{INPUT : BLOCKS.LEAD, 			OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 1000}, TEMPERATURE : 328, 	KEY : 'lead_block'},
		{INPUT : BLOCKS.NICKEL, 		OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 1000}, TEMPERATURE : 1453, KEY : 'nickel_block'},
		{INPUT : BLOCKS.SILVER, 		OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 1000}, TEMPERATURE : 961, 	KEY : 'silver_block'},
		{INPUT : BLOCKS.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 1000}, TEMPERATURE : 230, 	KEY : 'tin_block'},
		{INPUT : BLOCKS.ZINC, 			OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 1000}, TEMPERATURE : 420, 	KEY : 'zinc_block'},
		{INPUT : BLOCKS.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 1000}, TEMPERATURE : 270, 	KEY : 'bismuth_block'},
		{INPUT : BLOCKS.BERYLLIUM, 		OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 1000}, TEMPERATURE : 1200, KEY : 'beryllium_block'},
		{INPUT : BLOCKS.COBALT, 		OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 1000}, TEMPERATURE : 1500, KEY : 'cobalt_block'},
		{INPUT : BLOCKS.BORON, 			OUTPUT : { fluid : FLUIDS.BORON, 		amount : 1000}, TEMPERATURE : 2070, KEY : 'boron_block'},
		{INPUT : BLOCKS.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 1000}, TEMPERATURE : 1750, KEY : 'thorium_block'},
		{INPUT : BLOCKS.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 1000}, TEMPERATURE : 2490, KEY : 'iridium_block'},
		{INPUT : BLOCKS.TITANIUM, 		OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 1000}, TEMPERATURE : 1700, KEY : 'titanium_block'},
		{INPUT : BLOCKS.ANTIMONY, 		OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 1000}, TEMPERATURE : 630, 	KEY : 'antimony_block'},
		{INPUT : BLOCKS.TUNGSTEN, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 1000}, TEMPERATURE : 3400, KEY : 'tungsten_block'},
		{INPUT : BLOCKS.CHROMIUM, 		OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 1000}, TEMPERATURE : 1250, KEY : 'chromium_block'},
		{INPUT : BLOCKS.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 1000}, TEMPERATURE : 1100, KEY : 'uranium_block'},
		{INPUT : BLOCKS.PLATINUM, 		OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 1000}, TEMPERATURE : 1730, KEY : 'platinum_block'},
		{INPUT : BLOCKS.OSMIUM, 		OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 1000}, TEMPERATURE : 3025, KEY : 'osmium_block'},
		
		{INPUT : BLOCKS.BRONZE, 			OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 1000}, TEMPERATURE : 950,  KEY : 'bronze_block'},
		{INPUT : BLOCKS.BISMUTH_BRONZE, 	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 1000}, TEMPERATURE : 985,  KEY : 'bismuth_bronze_block'},
		{INPUT : BLOCKS.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 1000}, TEMPERATURE : 1070, KEY : 'black_bronze_block'},
		{INPUT : BLOCKS.BRASS, 				OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 1000}, TEMPERATURE : 930,  KEY : 'brass_block'},
		{INPUT : BLOCKS.ROSE_GOLD, 			OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 1000}, TEMPERATURE : 960,  KEY : 'rose_gold_block'},
		{INPUT : BLOCKS.STERLING_SILVER, 	OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 1000}, TEMPERATURE : 950,  KEY : 'sterling_silver_block'},
		{INPUT : BLOCKS.STEEL, 				OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 1000}, TEMPERATURE : 1540, KEY : 'steel_block'},
		{INPUT : BLOCKS.BLACK_STEEL, 		OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 1000}, TEMPERATURE : 1485, KEY : 'black_steel_block'},
		{INPUT : BLOCKS.BLUE_STEEL, 		OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 1000}, TEMPERATURE : 1540, KEY : 'blue_steel_block'},
		{INPUT : BLOCKS.RED_STEEL, 			OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 1000}, TEMPERATURE : 1540, KEY : 'red_steel_block'},
		{INPUT : BLOCKS.ALNICO, 			OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 1000}, TEMPERATURE : 1500, KEY : 'alnico_block'},
		{INPUT : BLOCKS.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 1000}, TEMPERATURE : 1500, KEY : 'beryllium_copper_block'},
		{INPUT : BLOCKS.CONSTANTAN, 		OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 1000}, TEMPERATURE : 1200, KEY : 'constantan_block'},
		{INPUT : BLOCKS.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 1000}, TEMPERATURE : 1200, KEY : 'electrum_block'},
		{INPUT : BLOCKS.FERROBORON, 		OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 1000}, TEMPERATURE : 3000, KEY : 'ferroboron_block'},
		{INPUT : BLOCKS.FLORENTINE_BRONZE, 	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 1000}, TEMPERATURE : 400,  KEY : 'florentine_bronze_block'},
		{INPUT : BLOCKS.INVAR, 				OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 1000}, TEMPERATURE : 1450, KEY : 'invar_block'},
		{INPUT : BLOCKS.MITHRIL, 			OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 1000}, TEMPERATURE : 940,  KEY : 'mithril_block'},
		{INPUT : BLOCKS.NICKEL_SILVER, 		OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 1000}, TEMPERATURE : 1450, KEY : 'nickel_silver_block'},
		{INPUT : BLOCKS.OSMIRIDIUM, 		OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 1000}, TEMPERATURE : 1500, KEY : 'osmiridium_block'},
		{INPUT : BLOCKS.PEWTER, 			OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 1000}, TEMPERATURE : 1500, KEY : 'pewter_block'},
		{INPUT : BLOCKS.SOLDER, 			OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 1000}, TEMPERATURE : 400,  KEY : 'solder_block'},
		{INPUT : BLOCKS.TUNGSTEN_STEEL, 	OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 1000}, TEMPERATURE : 3690, KEY : 'tungsten_steel_block'},
		
		{INPUT : GEARS.ALUMINUM, 		OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 200 }, TEMPERATURE : 660, 	KEY : 'aluminum_small_gear'},
		{INPUT : GEARS.COPPER,			OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 200 }, TEMPERATURE : 1080, KEY : 'copper_small_gear'},
		{INPUT : GEARS.GOLD, 			OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 200 }, TEMPERATURE : 1060, KEY : 'gold_small_gear'},
		{INPUT : GEARS.WROUGHT_IRON, 	OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 200 }, TEMPERATURE : 1536, KEY : 'wrought_iron_small_gear'},
		{INPUT : GEARS.LEAD, 			OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 200 }, TEMPERATURE : 328, 	KEY : 'lead_small_gear'},
		{INPUT : GEARS.NICKEL, 			OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 200 }, TEMPERATURE : 1453, KEY : 'nickel_small_gear'},
		{INPUT : GEARS.SILVER, 			OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 200 }, TEMPERATURE : 961, 	KEY : 'silver_small_gear'},
		{INPUT : GEARS.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 200 }, TEMPERATURE : 230, 	KEY : 'tin_small_gear'},
		{INPUT : GEARS.ZINC, 			OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 200 }, TEMPERATURE : 420, 	KEY : 'zinc_small_gear'},
		{INPUT : GEARS.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 200 }, TEMPERATURE : 270, 	KEY : 'bismuth_small_gear'},
		{INPUT : GEARS.BERYLLIUM, 		OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 200 }, TEMPERATURE : 1200, KEY : 'beryllium_small_gear'},
		{INPUT : GEARS.COBALT, 			OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 200 }, TEMPERATURE : 1500, KEY : 'cobalt_small_gear'},
		{INPUT : GEARS.BORON, 			OUTPUT : { fluid : FLUIDS.BORON, 		amount : 200 }, TEMPERATURE : 2070, KEY : 'boron_small_gear'},
		{INPUT : GEARS.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 200 }, TEMPERATURE : 1750, KEY : 'thorium_small_gear'},
		{INPUT : GEARS.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 200 }, TEMPERATURE : 2490, KEY : 'iridium_small_gear'},
		{INPUT : GEARS.TITANIUM, 		OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 200 }, TEMPERATURE : 1700, KEY : 'titanium_small_gear'},
		{INPUT : GEARS.ANTIMONY, 		OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 200 }, TEMPERATURE : 630, 	KEY : 'antimony_small_gear'},
		{INPUT : GEARS.TUNGSTEN, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 200 }, TEMPERATURE : 3400, KEY : 'tungsten_small_gear'},
		{INPUT : GEARS.CHROMIUM, 		OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 200 }, TEMPERATURE : 1250, KEY : 'chromium_small_gear'},
		{INPUT : GEARS.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 200 }, TEMPERATURE : 1100, KEY : 'uranium_small_gear'},
		{INPUT : GEARS.PLATINUM, 		OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 200 }, TEMPERATURE : 1730, KEY : 'platinum_small_gear'},
		{INPUT : GEARS.OSMIUM, 			OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 200 }, TEMPERATURE : 3025, KEY : 'osmium_small_gear'},
		
		{INPUT : GEARS.BRONZE, 				OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 200 }, TEMPERATURE : 950,  KEY : 'bronze_small_gear'},
		{INPUT : GEARS.BISMUTH_BRONZE,	 	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 200 }, TEMPERATURE : 985,  KEY : 'bismuth_bronze_small_gear'},
		{INPUT : GEARS.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 200 }, TEMPERATURE : 1070, KEY : 'black_bronze_small_gear'},
		{INPUT : GEARS.BRASS, 				OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 200 }, TEMPERATURE : 930,  KEY : 'brass_small_gear'},
		{INPUT : GEARS.ROSE_GOLD, 			OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 200 }, TEMPERATURE : 960,  KEY : 'rose_gold_small_gear'},
		{INPUT : GEARS.STERLING_SILVER, 	OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 200 }, TEMPERATURE : 950,  KEY : 'sterling_silver_small_gear'},
		{INPUT : GEARS.STEEL, 				OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 200 }, TEMPERATURE : 1540, KEY : 'steel_small_gear'},
		{INPUT : GEARS.BLACK_STEEL, 		OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 200 }, TEMPERATURE : 1485, KEY : 'black_steel_small_gear'},
		{INPUT : GEARS.BLUE_STEEL, 			OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'blue_steel_small_gear'},
		{INPUT : GEARS.RED_STEEL, 			OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'red_steel_small_gear'},
		{INPUT : GEARS.ALNICO, 				OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'alnico_small_gear'},
		{INPUT : GEARS.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 200 }, TEMPERATURE : 1500, KEY : 'beryllium_copper_small_gear'},
		{INPUT : GEARS.CONSTANTAN, 			OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'constantan_small_gear'},
		{INPUT : GEARS.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'electrum_small_gear'},
		{INPUT : GEARS.FERROBORON, 			OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 200 }, TEMPERATURE : 3000, KEY : 'ferroboron_small_gear'},
		{INPUT : GEARS.FLORENTINE_BRONZE, 	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 200 }, TEMPERATURE : 400,  KEY : 'florentine_bronze_small_gear'},
		{INPUT : GEARS.INVAR, 				OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 200 }, TEMPERATURE : 1450, KEY : 'invar_small_gear'},
		{INPUT : GEARS.MITHRIL, 			OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 200 }, TEMPERATURE : 940,  KEY : 'mithril_small_gear'},
		{INPUT : GEARS.NICKEL_SILVER, 		OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 200 }, TEMPERATURE : 1450, KEY : 'nickel_silver_small_gear'},
		{INPUT : GEARS.OSMIRIDIUM, 			OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 200 }, TEMPERATURE : 1500, KEY : 'osmiridium_small_gear'},
		{INPUT : GEARS.PEWTER, 				OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'pewter_small_gear'},
		{INPUT : GEARS.SOLDER, 				OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 200 }, TEMPERATURE : 400,  KEY : 'solder_small_gear'},
		{INPUT : GEARS.TUNGSTEN_STEEL, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 200 }, TEMPERATURE : 3690, KEY : 'tungsten_steel_small_gear'},
		
		{INPUT : GREATE_GEARS.ALUMINUM, 	OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 400 }, TEMPERATURE : 660, 	KEY : 'aluminum_large_gear'},
		{INPUT : GREATE_GEARS.COPPER,		OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 400 }, TEMPERATURE : 1080, KEY : 'copper_large_gear'},
		{INPUT : GREATE_GEARS.GOLD, 		OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 400 }, TEMPERATURE : 1060, KEY : 'gold_large_gear'},
		{INPUT : GREATE_GEARS.WROUGHT_IRON, OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 400 }, TEMPERATURE : 1536, KEY : 'wrought_iron_large_gear'},
		{INPUT : GREATE_GEARS.LEAD, 		OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 400 }, TEMPERATURE : 328, 	KEY : 'lead_large_gear'},
		{INPUT : GREATE_GEARS.NICKEL, 		OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 400 }, TEMPERATURE : 1453, KEY : 'nickel_large_gear'},
		{INPUT : GREATE_GEARS.SILVER, 		OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 400 }, TEMPERATURE : 961, 	KEY : 'silver_large_gear'},
		{INPUT : GREATE_GEARS.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 400 }, TEMPERATURE : 230, 	KEY : 'tin_large_gear'},
		{INPUT : GREATE_GEARS.ZINC, 		OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 400 }, TEMPERATURE : 420, 	KEY : 'zinc_large_gear'},
		{INPUT : GREATE_GEARS.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 400 }, TEMPERATURE : 270, 	KEY : 'bismuth_large_gear'},
		{INPUT : GREATE_GEARS.BERYLLIUM, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 400 }, TEMPERATURE : 1200, KEY : 'beryllium_large_gear'},
		{INPUT : GREATE_GEARS.COBALT, 		OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 400 }, TEMPERATURE : 1500, KEY : 'cobalt_large_gear'},
		{INPUT : GREATE_GEARS.BORON, 		OUTPUT : { fluid : FLUIDS.BORON, 		amount : 400 }, TEMPERATURE : 2070, KEY : 'boron_large_gear'},
		{INPUT : GREATE_GEARS.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 400 }, TEMPERATURE : 1750, KEY : 'thorium_large_gear'},
		{INPUT : GREATE_GEARS.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 400 }, TEMPERATURE : 2490, KEY : 'iridium_large_gear'},
		{INPUT : GREATE_GEARS.TITANIUM, 	OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 400 }, TEMPERATURE : 1700, KEY : 'titanium_large_gear'},
		{INPUT : GREATE_GEARS.ANTIMONY, 	OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 400 }, TEMPERATURE : 630, 	KEY : 'antimony_large_gear'},
		{INPUT : GREATE_GEARS.TUNGSTEN, 	OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 400 }, TEMPERATURE : 3400, KEY : 'tungsten_large_gear'},
		{INPUT : GREATE_GEARS.CHROMIUM, 	OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 400 }, TEMPERATURE : 1250, KEY : 'chromium_large_gear'},
		{INPUT : GREATE_GEARS.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 400 }, TEMPERATURE : 1100, KEY : 'uranium_large_gear'},
		{INPUT : GREATE_GEARS.PLATINUM, 	OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 400 }, TEMPERATURE : 1730, KEY : 'platinum_large_gear'},
		{INPUT : GREATE_GEARS.OSMIUM, 		OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 400 }, TEMPERATURE : 3025, KEY : 'osmium_large_gear'},
		
		{INPUT : GREATE_GEARS.BRONZE, 				OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 400 }, TEMPERATURE : 950,  KEY : 'bronze_large_gear'},
		{INPUT : GREATE_GEARS.BISMUTH_BRONZE,	 	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 400 }, TEMPERATURE : 985,  KEY : 'bismuth_bronze_large_gear'},
		{INPUT : GREATE_GEARS.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 400 }, TEMPERATURE : 1070, KEY : 'black_bronze_large_gear'},
		{INPUT : GREATE_GEARS.BRASS, 				OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 400 }, TEMPERATURE : 930,  KEY : 'brass_large_gear'},
		{INPUT : GREATE_GEARS.ROSE_GOLD, 			OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 400 }, TEMPERATURE : 960,  KEY : 'rose_gold_large_gear'},
		{INPUT : GREATE_GEARS.STERLING_SILVER, 		OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 400 }, TEMPERATURE : 950,  KEY : 'sterling_silver_large_gear'},
		{INPUT : GREATE_GEARS.STEEL, 				OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 400 }, TEMPERATURE : 1540, KEY : 'steel_large_gear'},
		{INPUT : GREATE_GEARS.BLACK_STEEL, 			OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 400 }, TEMPERATURE : 1485, KEY : 'black_steel_large_gear'},
		{INPUT : GREATE_GEARS.BLUE_STEEL, 			OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 400 }, TEMPERATURE : 1540, KEY : 'blue_steel_large_gear'},
		{INPUT : GREATE_GEARS.RED_STEEL, 			OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 400 }, TEMPERATURE : 1540, KEY : 'red_steel_large_gear'},
		{INPUT : GREATE_GEARS.ALNICO, 				OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 400 }, TEMPERATURE : 1500, KEY : 'alnico_large_gear'},
		{INPUT : GREATE_GEARS.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 400 }, TEMPERATURE : 1500, KEY : 'beryllium_copper_large_gear'},
		{INPUT : GREATE_GEARS.CONSTANTAN, 			OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 400 }, TEMPERATURE : 1200, KEY : 'constantan_large_gear'},
		{INPUT : GREATE_GEARS.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 400 }, TEMPERATURE : 1200, KEY : 'electrum_large_gear'},
		{INPUT : GREATE_GEARS.FERROBORON, 			OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 400 }, TEMPERATURE : 3000, KEY : 'ferroboron_large_gear'},
		{INPUT : GREATE_GEARS.FLORENTINE_BRONZE, 	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 400 }, TEMPERATURE : 400,  KEY : 'florentine_bronze_large_gear'},
		{INPUT : GREATE_GEARS.INVAR, 				OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 400 }, TEMPERATURE : 1450, KEY : 'invar_large_gear'},
		{INPUT : GREATE_GEARS.MITHRIL, 				OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 400 }, TEMPERATURE : 940,  KEY : 'mithril_large_gear'},
		{INPUT : GREATE_GEARS.NICKEL_SILVER, 		OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 400 }, TEMPERATURE : 1450, KEY : 'nickel_silver_large_gear'},
		{INPUT : GREATE_GEARS.OSMIRIDIUM, 			OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 400 }, TEMPERATURE : 1500, KEY : 'osmiridium_large_gear'},
		{INPUT : GREATE_GEARS.PEWTER, 				OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 400 }, TEMPERATURE : 1500, KEY : 'pewter_large_gear'},
		{INPUT : GREATE_GEARS.SOLDER, 				OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 400 }, TEMPERATURE : 400,  KEY : 'solder_large_gear'},
		{INPUT : GREATE_GEARS.TUNGSTEN_STEEL, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 400 }, TEMPERATURE : 3690, KEY : 'tungsten_steel_large_gear'},
		
		{INPUT : PLATES.ALUMINUM, 		OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 200 }, TEMPERATURE : 660, 	KEY : 'aluminum_plate'},
		{INPUT : PLATES.COPPER,			OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 200 }, TEMPERATURE : 1080, KEY : 'copper_plate'},
		{INPUT : PLATES.GOLD, 			OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 200 }, TEMPERATURE : 1060, KEY : 'gold_plate'},
		{INPUT : PLATES.WROUGHT_IRON, 	OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 200 }, TEMPERATURE : 1536, KEY : 'wrought_iron_plate'},
		{INPUT : PLATES.LEAD, 			OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 200 }, TEMPERATURE : 328, 	KEY : 'lead_plate'},
		{INPUT : PLATES.NICKEL, 		OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 200 }, TEMPERATURE : 1453, KEY : 'nickel_plate'},
		{INPUT : PLATES.SILVER, 		OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 200 }, TEMPERATURE : 961, 	KEY : 'silver_plate'},
		{INPUT : PLATES.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 200 }, TEMPERATURE : 230, 	KEY : 'tin_plate'},
		{INPUT : PLATES.ZINC, 			OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 200 }, TEMPERATURE : 420, 	KEY : 'zinc_plate'},
		{INPUT : PLATES.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 200 }, TEMPERATURE : 270, 	KEY : 'bismuth_plate'},
		{INPUT : PLATES.BERYLLIUM, 		OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 200 }, TEMPERATURE : 1200, KEY : 'beryllium_plate'},
		{INPUT : PLATES.COBALT, 		OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 200 }, TEMPERATURE : 1500, KEY : 'cobalt_plate'},
		{INPUT : PLATES.BORON, 			OUTPUT : { fluid : FLUIDS.BORON, 		amount : 200 }, TEMPERATURE : 2070, KEY : 'boron_plate'},
		{INPUT : PLATES.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 200 }, TEMPERATURE : 1750, KEY : 'thorium_plate'},
		{INPUT : PLATES.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 200 }, TEMPERATURE : 2490, KEY : 'iridium_plate'},
		{INPUT : PLATES.TITANIUM, 		OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 200 }, TEMPERATURE : 1700, KEY : 'titanium_plate'},
		{INPUT : PLATES.ANTIMONY, 		OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 200 }, TEMPERATURE : 630, 	KEY : 'antimony_plate'},
		{INPUT : PLATES.TUNGSTEN, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 200 }, TEMPERATURE : 3400, KEY : 'tungsten_plate'},
		{INPUT : PLATES.CHROMIUM, 		OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 200 }, TEMPERATURE : 1250, KEY : 'chromium_plate'},
		{INPUT : PLATES.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 200 }, TEMPERATURE : 1100, KEY : 'uranium_plate'},
		{INPUT : PLATES.PLATINUM, 		OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 200 }, TEMPERATURE : 1730, KEY : 'platinum_plate'},
		{INPUT : PLATES.OSMIUM, 		OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 200 }, TEMPERATURE : 3025, KEY : 'osmium_plate'},
		
		{INPUT : PLATES.BRONZE, 			OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 200 }, TEMPERATURE : 950,  KEY : 'bronze_plate'},
		{INPUT : PLATES.BISMUTH_BRONZE,	 	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 200 }, TEMPERATURE : 985,  KEY : 'bismuth_bronze_plate'},
		{INPUT : PLATES.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 200 }, TEMPERATURE : 1070, KEY : 'black_bronze_plate'},
		{INPUT : PLATES.BRASS, 				OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 200 }, TEMPERATURE : 930,  KEY : 'brass_plate'},
		{INPUT : PLATES.ROSE_GOLD, 			OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 200 }, TEMPERATURE : 960,  KEY : 'rose_gold_plate'},
		{INPUT : PLATES.STERLING_SILVER, 	OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 200 }, TEMPERATURE : 950,  KEY : 'sterling_silver_plate'},
		{INPUT : PLATES.STEEL, 				OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 200 }, TEMPERATURE : 1540, KEY : 'steel_plate'},
		{INPUT : PLATES.BLACK_STEEL, 		OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 200 }, TEMPERATURE : 1485, KEY : 'black_steel_plate'},
		{INPUT : PLATES.BLUE_STEEL, 		OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'blue_steel_plate'},
		{INPUT : PLATES.RED_STEEL, 			OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'red_steel_plate'},
		{INPUT : PLATES.ALNICO, 			OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'alnico_plate'},
		{INPUT : PLATES.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 200 }, TEMPERATURE : 1500, KEY : 'beryllium_copper_plate'},
		{INPUT : PLATES.CONSTANTAN, 		OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'constantan_plate'},
		{INPUT : PLATES.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'electrum_plate'},
		{INPUT : PLATES.FERROBORON, 		OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 200 }, TEMPERATURE : 3000, KEY : 'ferroboron_plate'},
		{INPUT : PLATES.FLORENTINE_BRONZE, 	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 200 }, TEMPERATURE : 400,  KEY : 'florentine_bronze_plate'},
		{INPUT : PLATES.INVAR, 				OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 200 }, TEMPERATURE : 1450, KEY : 'invar_plate'},
		{INPUT : PLATES.MITHRIL, 			OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 200 }, TEMPERATURE : 940,  KEY : 'mithril_plate'},
		{INPUT : PLATES.NICKEL_SILVER, 		OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 200 }, TEMPERATURE : 1450, KEY : 'nickel_silver_plate'},
		{INPUT : PLATES.OSMIRIDIUM, 		OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 200 }, TEMPERATURE : 1500, KEY : 'osmiridium_plate'},
		{INPUT : PLATES.PEWTER, 			OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'pewter_plate'},
		{INPUT : PLATES.SOLDER, 			OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 200 }, TEMPERATURE : 400,  KEY : 'solder_plate'},
		{INPUT : PLATES.TUNGSTEN_STEEL, 	OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 200 }, TEMPERATURE : 3690, KEY : 'tungsten_steel_plate'},
		
		{INPUT : GREATE_PLATES.ALUMINUM, 		OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 400 }, TEMPERATURE : 660, 	KEY : 'aluminum_large_plate'},
		{INPUT : GREATE_PLATES.COPPER,			OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 400 }, TEMPERATURE : 1080, KEY : 'copper_large_plate'},
		{INPUT : GREATE_PLATES.GOLD, 			OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 400 }, TEMPERATURE : 1060, KEY : 'gold_large_plate'},
		{INPUT : GREATE_PLATES.WROUGHT_IRON, 	OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 400 }, TEMPERATURE : 1536, KEY : 'wrought_iron_large_plate'},
		{INPUT : GREATE_PLATES.LEAD, 			OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 400 }, TEMPERATURE : 328, 	KEY : 'lead_large_plate'},
		{INPUT : GREATE_PLATES.NICKEL, 			OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 400 }, TEMPERATURE : 1453, KEY : 'nickel_large_plate'},
		{INPUT : GREATE_PLATES.SILVER, 			OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 400 }, TEMPERATURE : 961, 	KEY : 'silver_large_plate'},
		{INPUT : GREATE_PLATES.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 400 }, TEMPERATURE : 230, 	KEY : 'tin_large_plate'},
		{INPUT : GREATE_PLATES.ZINC, 			OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 400 }, TEMPERATURE : 420, 	KEY : 'zinc_large_plate'},
		{INPUT : GREATE_PLATES.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 400 }, TEMPERATURE : 270, 	KEY : 'bismuth_large_plate'},
		{INPUT : GREATE_PLATES.BERYLLIUM, 		OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 400 }, TEMPERATURE : 1200, KEY : 'beryllium_large_plate'},
		{INPUT : GREATE_PLATES.COBALT, 			OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 400 }, TEMPERATURE : 1500, KEY : 'cobalt_large_plate'},
		{INPUT : GREATE_PLATES.BORON, 			OUTPUT : { fluid : FLUIDS.BORON, 		amount : 400 }, TEMPERATURE : 2070, KEY : 'boron_large_plate'},
		{INPUT : GREATE_PLATES.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 400 }, TEMPERATURE : 1750, KEY : 'thorium_large_plate'},
		{INPUT : GREATE_PLATES.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 400 }, TEMPERATURE : 2490, KEY : 'iridium_large_plate'},
		{INPUT : GREATE_PLATES.TITANIUM, 		OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 400 }, TEMPERATURE : 1700, KEY : 'titanium_large_plate'},
		{INPUT : GREATE_PLATES.ANTIMONY, 		OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 400 }, TEMPERATURE : 630, 	KEY : 'antimony_large_plate'},
		{INPUT : GREATE_PLATES.TUNGSTEN, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 400 }, TEMPERATURE : 3400, KEY : 'tungsten_large_plate'},
		{INPUT : GREATE_PLATES.CHROMIUM, 		OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 400 }, TEMPERATURE : 1250, KEY : 'chromium_large_plate'},
		{INPUT : GREATE_PLATES.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 400 }, TEMPERATURE : 1100, KEY : 'uranium_large_plate'},
		{INPUT : GREATE_PLATES.PLATINUM, 		OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 400 }, TEMPERATURE : 1730, KEY : 'platinum_large_plate'},
		{INPUT : GREATE_PLATES.OSMIUM, 			OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 400 }, TEMPERATURE : 3025, KEY : 'osmium_large_plate'},
		
		{INPUT : GREATE_PLATES.BRONZE, 				OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 400 }, TEMPERATURE : 950,  KEY : 'bronze_large_plate'},
		{INPUT : GREATE_PLATES.BISMUTH_BRONZE,	 	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 400 }, TEMPERATURE : 985,  KEY : 'bismuth_bronze_large_plate'},
		{INPUT : GREATE_PLATES.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 400 }, TEMPERATURE : 1070, KEY : 'black_bronze_large_plate'},
		{INPUT : GREATE_PLATES.BRASS, 				OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 400 }, TEMPERATURE : 930,  KEY : 'brass_large_plate'},
		{INPUT : GREATE_PLATES.ROSE_GOLD, 			OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 400 }, TEMPERATURE : 960,  KEY : 'rose_gold_large_plate'},
		{INPUT : GREATE_PLATES.STERLING_SILVER, 	OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 400 }, TEMPERATURE : 950,  KEY : 'sterling_silver_large_plate'},
		{INPUT : GREATE_PLATES.STEEL, 				OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 400 }, TEMPERATURE : 1540, KEY : 'steel_large_plate'},
		{INPUT : GREATE_PLATES.BLACK_STEEL, 		OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 400 }, TEMPERATURE : 1485, KEY : 'black_steel_large_plate'},
		{INPUT : GREATE_PLATES.BLUE_STEEL, 			OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 400 }, TEMPERATURE : 1540, KEY : 'blue_steel_large_plate'},
		{INPUT : GREATE_PLATES.RED_STEEL, 			OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 400 }, TEMPERATURE : 1540, KEY : 'red_steel_large_plate'},
		{INPUT : GREATE_PLATES.ALNICO, 				OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 400 }, TEMPERATURE : 1500, KEY : 'alnico_large_plate'},
		{INPUT : GREATE_PLATES.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 400 }, TEMPERATURE : 1500, KEY : 'beryllium_copper_large_plate'},
		{INPUT : GREATE_PLATES.CONSTANTAN, 			OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 400 }, TEMPERATURE : 1200, KEY : 'constantan_large_plate'},
		{INPUT : GREATE_PLATES.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 400 }, TEMPERATURE : 1200, KEY : 'electrum_large_plate'},
		{INPUT : GREATE_PLATES.FERROBORON, 			OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 400 }, TEMPERATURE : 3000, KEY : 'ferroboron_large_plate'},
		{INPUT : GREATE_PLATES.FLORENTINE_BRONZE, 	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 400 }, TEMPERATURE : 400,  KEY : 'florentine_bronze_large_plate'},
		{INPUT : GREATE_PLATES.INVAR, 				OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 400 }, TEMPERATURE : 1450, KEY : 'invar_large_plate'},
		{INPUT : GREATE_PLATES.MITHRIL, 			OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 400 }, TEMPERATURE : 940,  KEY : 'mithril_large_plate'},
		{INPUT : GREATE_PLATES.NICKEL_SILVER, 		OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 400 }, TEMPERATURE : 1450, KEY : 'nickel_silver_large_plate'},
		{INPUT : GREATE_PLATES.OSMIRIDIUM, 			OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 400 }, TEMPERATURE : 1500, KEY : 'osmiridium_large_plate'},
		{INPUT : GREATE_PLATES.PEWTER, 				OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 400 }, TEMPERATURE : 1500, KEY : 'pewter_large_plate'},
		{INPUT : GREATE_PLATES.SOLDER, 				OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 400 }, TEMPERATURE : 400,  KEY : 'solder_large_plate'},
		{INPUT : GREATE_PLATES.TUNGSTEN_STEEL, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 400 }, TEMPERATURE : 3690, KEY : 'tungsten_steel_large_plate'},
		
		{INPUT : GREATE_RODS.ALUMINUM, 		OUTPUT : { fluid : FLUIDS.ALUMINUM, 	amount : 200 }, TEMPERATURE : 660, 	KEY : 'aluminum_large_rod'},
		{INPUT : GREATE_RODS.COPPER,		OUTPUT : { fluid : FLUIDS.COPPER, 		amount : 200 }, TEMPERATURE : 1080, KEY : 'copper_large_rod'},
		{INPUT : GREATE_RODS.GOLD, 			OUTPUT : { fluid : FLUIDS.GOLD, 		amount : 200 }, TEMPERATURE : 1060, KEY : 'gold_large_rod'},
		{INPUT : GREATE_RODS.WROUGHT_IRON, 	OUTPUT : { fluid : FLUIDS.WROUGHT_IRON, amount : 200 }, TEMPERATURE : 1536, KEY : 'wrought_iron_large_rod'},
		{INPUT : GREATE_RODS.LEAD, 			OUTPUT : { fluid : FLUIDS.LEAD, 		amount : 200 }, TEMPERATURE : 328, 	KEY : 'lead_large_rod'},
		{INPUT : GREATE_RODS.NICKEL, 		OUTPUT : { fluid : FLUIDS.NICKEL, 		amount : 200 }, TEMPERATURE : 1453, KEY : 'nickel_large_rod'},
		{INPUT : GREATE_RODS.SILVER, 		OUTPUT : { fluid : FLUIDS.SILVER, 		amount : 200 }, TEMPERATURE : 961, 	KEY : 'silver_large_rod'},
		{INPUT : GREATE_RODS.TIN, 			OUTPUT : { fluid : FLUIDS.TIN, 			amount : 200 }, TEMPERATURE : 230, 	KEY : 'tin_large_rod'},
		{INPUT : GREATE_RODS.ZINC, 			OUTPUT : { fluid : FLUIDS.ZINC, 		amount : 200 }, TEMPERATURE : 420, 	KEY : 'zinc_large_rod'},
		{INPUT : GREATE_RODS.BISMUTH, 		OUTPUT : { fluid : FLUIDS.BISMUTH, 		amount : 200 }, TEMPERATURE : 270, 	KEY : 'bismuth_large_rod'},
		{INPUT : GREATE_RODS.BERYLLIUM, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM, 	amount : 200 }, TEMPERATURE : 1200, KEY : 'beryllium_large_rod'},
		{INPUT : GREATE_RODS.COBALT, 		OUTPUT : { fluid : FLUIDS.COBALT, 		amount : 200 }, TEMPERATURE : 1500, KEY : 'cobalt_large_rod'},
		{INPUT : GREATE_RODS.BORON, 		OUTPUT : { fluid : FLUIDS.BORON, 		amount : 200 }, TEMPERATURE : 2070, KEY : 'boron_large_rod'},
		{INPUT : GREATE_RODS.THORIUM, 		OUTPUT : { fluid : FLUIDS.THORIUM, 		amount : 200 }, TEMPERATURE : 1750, KEY : 'thorium_large_rod'},
		{INPUT : GREATE_RODS.IRIDIUM, 		OUTPUT : { fluid : FLUIDS.IRIDIUM, 		amount : 200 }, TEMPERATURE : 2490, KEY : 'iridium_large_rod'},
		{INPUT : GREATE_RODS.TITANIUM, 		OUTPUT : { fluid : FLUIDS.TITANIUM, 	amount : 200 }, TEMPERATURE : 1700, KEY : 'titanium_large_rod'},
		{INPUT : GREATE_RODS.ANTIMONY, 		OUTPUT : { fluid : FLUIDS.ANTIMONY, 	amount : 200 }, TEMPERATURE : 630, 	KEY : 'antimony_large_rod'},
		{INPUT : GREATE_RODS.TUNGSTEN, 		OUTPUT : { fluid : FLUIDS.TUNGSTEN, 	amount : 200 }, TEMPERATURE : 3400, KEY : 'tungsten_large_rod'},
		{INPUT : GREATE_RODS.CHROMIUM, 		OUTPUT : { fluid : FLUIDS.CHROMIUM, 	amount : 200 }, TEMPERATURE : 1250, KEY : 'chromium_large_rod'},
		{INPUT : GREATE_RODS.URANIUM, 		OUTPUT : { fluid : FLUIDS.URANIUM, 		amount : 200 }, TEMPERATURE : 1100, KEY : 'uranium_large_rod'},
		{INPUT : GREATE_RODS.PLATINUM, 		OUTPUT : { fluid : FLUIDS.PLATINUM, 	amount : 200 }, TEMPERATURE : 1730, KEY : 'platinum_large_rod'},
		{INPUT : GREATE_RODS.OSMIUM, 		OUTPUT : { fluid : FLUIDS.OSMIUM, 		amount : 200 }, TEMPERATURE : 3025, KEY : 'osmium_large_rod'},
		
		{INPUT : GREATE_RODS.BRONZE, 			OUTPUT : { fluid : FLUIDS.BRONZE, 				amount : 200 }, TEMPERATURE : 950,  KEY : 'bronze_large_rod'},
		{INPUT : GREATE_RODS.BISMUTH_BRONZE,	OUTPUT : { fluid : FLUIDS.BISMUTH_BRONZE, 		amount : 200 }, TEMPERATURE : 985,  KEY : 'bismuth_bronze_large_rod'},
		{INPUT : GREATE_RODS.BLACK_BRONZE, 		OUTPUT : { fluid : FLUIDS.BLACK_BRONZE, 		amount : 200 }, TEMPERATURE : 1070, KEY : 'black_bronze_large_rod'},
		{INPUT : GREATE_RODS.BRASS, 			OUTPUT : { fluid : FLUIDS.BRASS, 				amount : 200 }, TEMPERATURE : 930,  KEY : 'brass_large_rod'},
		{INPUT : GREATE_RODS.ROSE_GOLD, 		OUTPUT : { fluid : FLUIDS.ROSE_GOLD, 			amount : 200 }, TEMPERATURE : 960,  KEY : 'rose_gold_large_rod'},
		{INPUT : GREATE_RODS.STERLING_SILVER, 	OUTPUT : { fluid : FLUIDS.STERLING_SILVER, 		amount : 200 }, TEMPERATURE : 950,  KEY : 'sterling_silver_large_rod'},
		{INPUT : GREATE_RODS.STEEL, 			OUTPUT : { fluid : FLUIDS.STEEL, 				amount : 200 }, TEMPERATURE : 1540, KEY : 'steel_large_rod'},
		{INPUT : GREATE_RODS.BLACK_STEEL, 		OUTPUT : { fluid : FLUIDS.BLACK_STEEL, 			amount : 200 }, TEMPERATURE : 1485, KEY : 'black_steel_large_rod'},
		{INPUT : GREATE_RODS.BLUE_STEEL, 		OUTPUT : { fluid : FLUIDS.BLUE_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'blue_steel_large_rod'},
		{INPUT : GREATE_RODS.RED_STEEL, 		OUTPUT : { fluid : FLUIDS.RED_STEEL, 			amount : 200 }, TEMPERATURE : 1540, KEY : 'red_steel_large_rod'},
		{INPUT : GREATE_RODS.ALNICO, 			OUTPUT : { fluid : FLUIDS.ALNICO, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'alnico_large_rod'},
		{INPUT : GREATE_RODS.BERYLLIUM_COPPER, 	OUTPUT : { fluid : FLUIDS.BERYLLIUM_COPPER, 	amount : 200 }, TEMPERATURE : 1500, KEY : 'beryllium_copper_large_rod'},
		{INPUT : GREATE_RODS.CONSTANTAN, 		OUTPUT : { fluid : FLUIDS.CONSTANTAN, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'constantan_large_rod'},
		{INPUT : GREATE_RODS.ELECTRUM, 			OUTPUT : { fluid : FLUIDS.ELECTRUM, 			amount : 200 }, TEMPERATURE : 1200, KEY : 'electrum_large_rod'},
		{INPUT : GREATE_RODS.FERROBORON, 		OUTPUT : { fluid : FLUIDS.FERROBORON, 			amount : 200 }, TEMPERATURE : 3000, KEY : 'ferroboron_large_rod'},
		{INPUT : GREATE_RODS.FLORENTINE_BRONZE,	OUTPUT : { fluid : FLUIDS.FLORENTINE_BRONZE,	amount : 200 }, TEMPERATURE : 400,  KEY : 'florentine_bronze_large_rod'},
		{INPUT : GREATE_RODS.INVAR, 			OUTPUT : { fluid : FLUIDS.INVAR, 				amount : 200 }, TEMPERATURE : 1450, KEY : 'invar_large_rod'},
		{INPUT : GREATE_RODS.MITHRIL, 			OUTPUT : { fluid : FLUIDS.MITHRIL, 				amount : 200 }, TEMPERATURE : 940,  KEY : 'mithril_large_rod'},
		{INPUT : GREATE_RODS.NICKEL_SILVER, 	OUTPUT : { fluid : FLUIDS.NICKEL_SILVER, 		amount : 200 }, TEMPERATURE : 1450, KEY : 'nickel_silver_large_rod'},
		{INPUT : GREATE_RODS.OSMIRIDIUM, 		OUTPUT : { fluid : FLUIDS.OSMIRIDIUM, 			amount : 200 }, TEMPERATURE : 1500, KEY : 'osmiridium_large_rod'},
		{INPUT : GREATE_RODS.PEWTER, 			OUTPUT : { fluid : FLUIDS.PEWTER, 				amount : 200 }, TEMPERATURE : 1500, KEY : 'pewter_large_rod'},
		{INPUT : GREATE_RODS.SOLDER, 			OUTPUT : { fluid : FLUIDS.SOLDER, 				amount : 200 }, TEMPERATURE : 400,  KEY : 'solder_large_rod'},
		{INPUT : GREATE_RODS.TUNGSTEN_STEEL, 	OUTPUT : { fluid : FLUIDS.TUNGSTEN_STEEL, 		amount : 200 }, TEMPERATURE : 3690, KEY : 'tungsten_steel_large_rod'}
		
	]
	recipes.forEach(recipe=>{
		event.custom({ 
			type: 'tfc:heating',
			ingredient: { 
				item: recipe.INPUT 
			},
			result_fluid: recipe.OUTPUT,
			temperature: recipe.TEMPERATURE
		}).id(`${recipe.INPUT.slice(0,recipe.INPUT.indexOf(':'))}:heating/metal/${recipe.KEY}`)
	})
})