onEvent('recipes', event => {
	const EXP='create:experience_nugget'
	const recipes = [
		{INPUT: ORES.NORMAL.ALUMINUM, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_aluminum_ore'},
		{INPUT: ORES.NORMAL.LEAD, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_lead_ore'},
		{INPUT: ORES.NORMAL.URANIUM, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM,  		count: 5}, {item : CRUSHED_ORES.URANIUM,  		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_uranium_ore'},
		{INPUT: ORES.NORMAL.BAUXITE, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM,		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_bauxite_ore'},
		{INPUT: ORES.NORMAL.COPPER, 		OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_copper_ore'},
		{INPUT: ORES.NORMAL.MALACHITE, 		OUTPUT: [{item : CRUSHED_ORES.COPPER,			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_malachite_ore'},
		{INPUT: ORES.NORMAL.TETRAHEDRITE,	OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_tetrahedrite_ore'},
		{INPUT: ORES.NORMAL.GOLD, 			OUTPUT: [{item : CRUSHED_ORES.GOLD,				count: 5}, {item : CRUSHED_ORES.GOLD,			chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_gold_ore'},
		{INPUT: ORES.NORMAL.MAGNETITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_magnetite_ore'},
		{INPUT: ORES.NORMAL.HEMATITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_hematite_ore'},
		{INPUT: ORES.NORMAL.LIMONITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_limonite_ore'},
		{INPUT: ORES.NORMAL.GALENA, 		OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_galena_ore'},
		{INPUT: ORES.NORMAL.GARNIERITE, 	OUTPUT: [{item : CRUSHED_ORES.NICKEL, 			count: 5}, {item : CRUSHED_ORES.NICKEL, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_garnierite_ore'},
		{INPUT: ORES.NORMAL.SILVER, 		OUTPUT: [{item : CRUSHED_ORES.SILVER, 			count: 5}, {item : CRUSHED_ORES.SILVER, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_silver_ore'},
		{INPUT: ORES.NORMAL.CASSITERITE, 	OUTPUT: [{item : CRUSHED_ORES.TIN, 				count: 5}, {item : CRUSHED_ORES.TIN, 			chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_cassiterite_ore'},
		{INPUT: ORES.NORMAL.SPHALERITE, 	OUTPUT: [{item : CRUSHED_ORES.ZINC, 			count: 5}, {item : CRUSHED_ORES.ZINC,			chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_sphalerite_ore'},
		{INPUT: ORES.NORMAL.BISMUTHINITE, 	OUTPUT: [{item : CRUSHED_ORES.BISMUTHINITE, 	count: 5}, {item : CRUSHED_ORES.BISMUTHINITE,	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_bismuthinite_ore'},
		{INPUT: ORES.NORMAL.BERTRANDITE, 	OUTPUT: [{item : CRUSHED_ORES.BERTRANDITE, 		count: 5}, {item : CRUSHED_ORES.BERTRANDITE, 	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_bertrandite_ore'},
		{INPUT: ORES.NORMAL.COBALTITE, 		OUTPUT: [{item : CRUSHED_ORES.COBALTITE, 		count: 5}, {item : CRUSHED_ORES.COBALTITE, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_cobaltite_ore'},
		{INPUT: ORES.NORMAL.KERNITE, 		OUTPUT: [{item : CRUSHED_ORES.KERNITE, 			count: 5}, {item : CRUSHED_ORES.KERNITE, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_kernite_ore'},
		{INPUT: ORES.NORMAL.MONAZITE, 		OUTPUT: [{item : CRUSHED_ORES.MONAZITE, 		count: 5}, {item : CRUSHED_ORES.MONAZITE,		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_monazite_ore'},
		{INPUT: ORES.NORMAL.IRIDIUM, 		OUTPUT: [{item : CRUSHED_ORES.IRIDIUM, 			count: 5}, {item : CRUSHED_ORES.IRIDIUM, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_iridium_ore'},
		{INPUT: ORES.NORMAL.RUTILE, 		OUTPUT: [{item : CRUSHED_ORES.RUTILE, 			count: 5}, {item : CRUSHED_ORES.RUTILE, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_rutile_ore'},
		{INPUT: ORES.NORMAL.STIBNITE, 		OUTPUT: [{item : CRUSHED_ORES.STIBNITE, 		count: 5}, {item : CRUSHED_ORES.STIBNITE, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_stibnite_ore'},
		{INPUT: ORES.NORMAL.WOLFRAMITE, 	OUTPUT: [{item : CRUSHED_ORES.WOLFRAMITE, 		count: 5}, {item : CRUSHED_ORES.WOLFRAMITE, 	chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_wolframite_ore'},
		{INPUT: ORES.NORMAL.CHROMITE, 		OUTPUT: [{item : CRUSHED_ORES.CHROMITE, 		count: 5}, {item : CRUSHED_ORES.CHROMITE, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_chromite_ore'},
		{INPUT: ORES.NORMAL.URANINITE, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM, 			count: 5}, {item : CRUSHED_ORES.URANIUM, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_uraninite_ore'},
		{INPUT: ORES.NORMAL.PLATINUM, 		OUTPUT: [{item : CRUSHED_ORES.PLATINUM, 		count: 5}, {item : CRUSHED_ORES.PLATINUM, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_platinum_ore'},
		{INPUT: ORES.NORMAL.OSMIUM, 		OUTPUT: [{item : CRUSHED_ORES.OSMIUM, 			count: 5}, {item : CRUSHED_ORES.OSMIUM, 		chance: 0.25 },{item: EXP, chance: 0.5 }], TIME: 400 , KEY: 'normal_native_osmium_ore'},
		
		{INPUT: ORES.POOR.ALUMINUM, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_aluminum_ore'},
		{INPUT: ORES.POOR.LEAD, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_lead_ore'},
		{INPUT: ORES.POOR.URANIUM, 			OUTPUT: [{item : CRUSHED_ORES.URANIUM,  		count: 5}, {item : CRUSHED_ORES.URANIUM,  		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_uranium_ore'},
		{INPUT: ORES.POOR.BAUXITE, 			OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM,		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_bauxite_ore'},
		{INPUT: ORES.POOR.COPPER, 			OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_copper_ore'},
		{INPUT: ORES.POOR.MALACHITE, 		OUTPUT: [{item : CRUSHED_ORES.COPPER,			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_malachite_ore'},
		{INPUT: ORES.POOR.TETRAHEDRITE,		OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_tetrahedrite_ore'},
		{INPUT: ORES.POOR.GOLD, 			OUTPUT: [{item : CRUSHED_ORES.GOLD,				count: 5}, {item : CRUSHED_ORES.GOLD,			chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_gold_ore'},
		{INPUT: ORES.POOR.MAGNETITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_magnetite_ore'},
		{INPUT: ORES.POOR.HEMATITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_hematite_ore'},
		{INPUT: ORES.POOR.LIMONITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_limonite_ore'},
		{INPUT: ORES.POOR.GALENA, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_galena_ore'},
		{INPUT: ORES.POOR.GARNIERITE, 		OUTPUT: [{item : CRUSHED_ORES.NICKEL, 			count: 5}, {item : CRUSHED_ORES.NICKEL, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_garnierite_ore'},
		{INPUT: ORES.POOR.SILVER, 			OUTPUT: [{item : CRUSHED_ORES.SILVER, 			count: 5}, {item : CRUSHED_ORES.SILVER, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_silver_ore'},
		{INPUT: ORES.POOR.CASSITERITE, 		OUTPUT: [{item : CRUSHED_ORES.TIN, 				count: 5}, {item : CRUSHED_ORES.TIN, 			chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_cassiterite_ore'},
		{INPUT: ORES.POOR.SPHALERITE, 		OUTPUT: [{item : CRUSHED_ORES.ZINC, 			count: 5}, {item : CRUSHED_ORES.ZINC,			chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_sphalerite_ore'},
		{INPUT: ORES.POOR.BISMUTHINITE, 	OUTPUT: [{item : CRUSHED_ORES.BISMUTHINITE, 	count: 5}, {item : CRUSHED_ORES.BISMUTHINITE,	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_bismuthinite_ore'},
		{INPUT: ORES.POOR.BERTRANDITE, 		OUTPUT: [{item : CRUSHED_ORES.BERTRANDITE, 		count: 5}, {item : CRUSHED_ORES.BERTRANDITE, 	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_bertrandite_ore'},
		{INPUT: ORES.POOR.COBALTITE, 		OUTPUT: [{item : CRUSHED_ORES.COBALTITE, 		count: 5}, {item : CRUSHED_ORES.COBALTITE, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_cobaltite_ore'},
		{INPUT: ORES.POOR.KERNITE, 			OUTPUT: [{item : CRUSHED_ORES.KERNITE, 			count: 5}, {item : CRUSHED_ORES.KERNITE, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_kernite_ore'},
		{INPUT: ORES.POOR.MONAZITE, 		OUTPUT: [{item : CRUSHED_ORES.MONAZITE, 		count: 5}, {item : CRUSHED_ORES.MONAZITE,		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_monazite_ore'},
		{INPUT: ORES.POOR.IRIDIUM, 			OUTPUT: [{item : CRUSHED_ORES.IRIDIUM, 			count: 5}, {item : CRUSHED_ORES.IRIDIUM, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_iridium_ore'},
		{INPUT: ORES.POOR.RUTILE, 			OUTPUT: [{item : CRUSHED_ORES.RUTILE, 			count: 5}, {item : CRUSHED_ORES.RUTILE, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_rutile_ore'},
		{INPUT: ORES.POOR.STIBNITE, 		OUTPUT: [{item : CRUSHED_ORES.STIBNITE, 		count: 5}, {item : CRUSHED_ORES.STIBNITE, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_stibnite_ore'},
		{INPUT: ORES.POOR.WOLFRAMITE, 		OUTPUT: [{item : CRUSHED_ORES.WOLFRAMITE, 		count: 5}, {item : CRUSHED_ORES.WOLFRAMITE, 	chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_wolframite_ore'},
		{INPUT: ORES.POOR.CHROMITE, 		OUTPUT: [{item : CRUSHED_ORES.CHROMITE, 		count: 5}, {item : CRUSHED_ORES.CHROMITE, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_chromite_ore'},
		{INPUT: ORES.POOR.URANINITE, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM, 			count: 5}, {item : CRUSHED_ORES.URANIUM, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_uraninite_ore'},
		{INPUT: ORES.POOR.PLATINUM, 		OUTPUT: [{item : CRUSHED_ORES.PLATINUM, 		count: 5}, {item : CRUSHED_ORES.PLATINUM, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_platinum_ore'},
		{INPUT: ORES.POOR.OSMIUM, 			OUTPUT: [{item : CRUSHED_ORES.OSMIUM, 			count: 5}, {item : CRUSHED_ORES.OSMIUM, 		chance: 0.10 },{item: EXP, chance: 0.15 }], TIME: 400 , KEY: 'poor_native_osmium_ore'},
		
		{INPUT: ORES.RICH.ALUMINUM, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_aluminum_ore'},
		{INPUT: ORES.RICH.LEAD, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_lead_ore'},
		{INPUT: ORES.RICH.URANIUM, 			OUTPUT: [{item : CRUSHED_ORES.URANIUM,  		count: 5}, {item : CRUSHED_ORES.URANIUM,  		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_uranium_ore'},
		{INPUT: ORES.RICH.BAUXITE, 			OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM,		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_bauxite_ore'},
		{INPUT: ORES.RICH.COPPER, 			OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_copper_ore'},
		{INPUT: ORES.RICH.MALACHITE, 		OUTPUT: [{item : CRUSHED_ORES.COPPER,			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_malachite_ore'},
		{INPUT: ORES.RICH.TETRAHEDRITE,		OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_tetrahedrite_ore'},
		{INPUT: ORES.RICH.GOLD, 			OUTPUT: [{item : CRUSHED_ORES.GOLD,				count: 5}, {item : CRUSHED_ORES.GOLD,			chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_gold_ore'},
		{INPUT: ORES.RICH.MAGNETITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_magnetite_ore'},
		{INPUT: ORES.RICH.HEMATITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_hematite_ore'},
		{INPUT: ORES.RICH.LIMONITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_limonite_ore'},
		{INPUT: ORES.RICH.GALENA, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_galena_ore'},
		{INPUT: ORES.RICH.GARNIERITE, 		OUTPUT: [{item : CRUSHED_ORES.NICKEL, 			count: 5}, {item : CRUSHED_ORES.NICKEL, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_garnierite_ore'},
		{INPUT: ORES.RICH.SILVER, 			OUTPUT: [{item : CRUSHED_ORES.SILVER, 			count: 5}, {item : CRUSHED_ORES.SILVER, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_silver_ore'},
		{INPUT: ORES.RICH.CASSITERITE, 		OUTPUT: [{item : CRUSHED_ORES.TIN, 				count: 5}, {item : CRUSHED_ORES.TIN, 			chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_cassiterite_ore'},
		{INPUT: ORES.RICH.SPHALERITE, 		OUTPUT: [{item : CRUSHED_ORES.ZINC, 			count: 5}, {item : CRUSHED_ORES.ZINC,			chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_sphalerite_ore'},
		{INPUT: ORES.RICH.BISMUTHINITE, 	OUTPUT: [{item : CRUSHED_ORES.BISMUTHINITE, 	count: 5}, {item : CRUSHED_ORES.BISMUTHINITE,	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_bismuthinite_ore'},
		{INPUT: ORES.RICH.BERTRANDITE, 		OUTPUT: [{item : CRUSHED_ORES.BERTRANDITE, 		count: 5}, {item : CRUSHED_ORES.BERTRANDITE, 	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_bertrandite_ore'},
		{INPUT: ORES.RICH.COBALTITE, 		OUTPUT: [{item : CRUSHED_ORES.COBALTITE, 		count: 5}, {item : CRUSHED_ORES.COBALTITE, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_cobaltite_ore'},
		{INPUT: ORES.RICH.KERNITE, 			OUTPUT: [{item : CRUSHED_ORES.KERNITE, 			count: 5}, {item : CRUSHED_ORES.KERNITE, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_kernite_ore'},
		{INPUT: ORES.RICH.MONAZITE, 		OUTPUT: [{item : CRUSHED_ORES.MONAZITE, 		count: 5}, {item : CRUSHED_ORES.MONAZITE,		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_monazite_ore'},
		{INPUT: ORES.RICH.IRIDIUM, 			OUTPUT: [{item : CRUSHED_ORES.IRIDIUM, 			count: 5}, {item : CRUSHED_ORES.IRIDIUM, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_iridium_ore'},
		{INPUT: ORES.RICH.RUTILE, 			OUTPUT: [{item : CRUSHED_ORES.RUTILE, 			count: 5}, {item : CRUSHED_ORES.RUTILE, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_rutile_ore'},
		{INPUT: ORES.RICH.STIBNITE, 		OUTPUT: [{item : CRUSHED_ORES.STIBNITE, 		count: 5}, {item : CRUSHED_ORES.STIBNITE, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_stibnite_ore'},
		{INPUT: ORES.RICH.WOLFRAMITE, 		OUTPUT: [{item : CRUSHED_ORES.WOLFRAMITE, 		count: 5}, {item : CRUSHED_ORES.WOLFRAMITE, 	chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_wolframite_ore'},
		{INPUT: ORES.RICH.CHROMITE, 		OUTPUT: [{item : CRUSHED_ORES.CHROMITE, 		count: 5}, {item : CRUSHED_ORES.CHROMITE, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_chromite_ore'},
		{INPUT: ORES.RICH.URANINITE, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM, 			count: 5}, {item : CRUSHED_ORES.URANIUM, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_uraninite_ore'},
		{INPUT: ORES.RICH.PLATINUM, 		OUTPUT: [{item : CRUSHED_ORES.PLATINUM, 		count: 5}, {item : CRUSHED_ORES.PLATINUM, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_platinum_ore'},
		{INPUT: ORES.RICH.OSMIUM, 			OUTPUT: [{item : CRUSHED_ORES.OSMIUM, 			count: 5}, {item : CRUSHED_ORES.OSMIUM, 		chance: 0.50 },{item: EXP, chance: 0.75 }], TIME: 400 , KEY: 'rich_native_osmium_ore'},
		
		{INPUT: ORES.SMALL.ALUMINUM, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_aluminum_ore'},
		{INPUT: ORES.SMALL.LEAD, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_lead_ore'},
		{INPUT: ORES.SMALL.URANIUM, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM,  		count: 5}, {item : CRUSHED_ORES.URANIUM,  		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_uranium_ore'},
		{INPUT: ORES.SMALL.BAUXITE, 		OUTPUT: [{item : CRUSHED_ORES.ALUMINUM, 		count: 5}, {item : CRUSHED_ORES.ALUMINUM,		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_bauxite_ore'},
		{INPUT: ORES.SMALL.COPPER, 			OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_copper_ore'},
		{INPUT: ORES.SMALL.MALACHITE, 		OUTPUT: [{item : CRUSHED_ORES.COPPER,			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_malachite_ore'},
		{INPUT: ORES.SMALL.TETRAHEDRITE,	OUTPUT: [{item : CRUSHED_ORES.COPPER, 			count: 5}, {item : CRUSHED_ORES.COPPER, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_tetrahedrite_ore'},
		{INPUT: ORES.SMALL.GOLD, 			OUTPUT: [{item : CRUSHED_ORES.GOLD,				count: 5}, {item : CRUSHED_ORES.GOLD,			chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_gold_ore'},
		{INPUT: ORES.SMALL.MAGNETITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_magnetite_ore'},
		{INPUT: ORES.SMALL.HEMATITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_hematite_ore'},
		{INPUT: ORES.SMALL.LIMONITE, 		OUTPUT: [{item : CRUSHED_ORES.WROUGHT_IRON, 	count: 5}, {item : CRUSHED_ORES.WROUGHT_IRON, 	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_limonite_ore'},
		{INPUT: ORES.SMALL.GALENA, 			OUTPUT: [{item : CRUSHED_ORES.LEAD, 			count: 5}, {item : CRUSHED_ORES.LEAD, 			chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_galena_ore'},
		{INPUT: ORES.SMALL.GARNIERITE, 		OUTPUT: [{item : CRUSHED_ORES.NICKEL, 			count: 5}, {item : CRUSHED_ORES.NICKEL, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_garnierite_ore'},
		{INPUT: ORES.SMALL.SILVER, 			OUTPUT: [{item : CRUSHED_ORES.SILVER, 			count: 5}, {item : CRUSHED_ORES.SILVER, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_silver_ore'},
		{INPUT: ORES.SMALL.CASSITERITE, 	OUTPUT: [{item : CRUSHED_ORES.TIN, 				count: 5}, {item : CRUSHED_ORES.TIN, 			chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_cassiterite_ore'},
		{INPUT: ORES.SMALL.SPHALERITE, 		OUTPUT: [{item : CRUSHED_ORES.ZINC, 			count: 5}, {item : CRUSHED_ORES.ZINC,			chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_sphalerite_ore'},
		{INPUT: ORES.SMALL.BISMUTHINITE, 	OUTPUT: [{item : CRUSHED_ORES.BISMUTHINITE, 	count: 5}, {item : CRUSHED_ORES.BISMUTHINITE,	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_bismuthinite_ore'},
		{INPUT: ORES.SMALL.BERTRANDITE, 	OUTPUT: [{item : CRUSHED_ORES.BERTRANDITE, 		count: 5}, {item : CRUSHED_ORES.BERTRANDITE, 	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_bertrandite_ore'},
		{INPUT: ORES.SMALL.COBALTITE, 		OUTPUT: [{item : CRUSHED_ORES.COBALTITE, 		count: 5}, {item : CRUSHED_ORES.COBALTITE, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_cobaltite_ore'},
		{INPUT: ORES.SMALL.KERNITE, 		OUTPUT: [{item : CRUSHED_ORES.KERNITE, 			count: 5}, {item : CRUSHED_ORES.KERNITE, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_kernite_ore'},
		{INPUT: ORES.SMALL.MONAZITE, 		OUTPUT: [{item : CRUSHED_ORES.MONAZITE, 		count: 5}, {item : CRUSHED_ORES.MONAZITE,		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_monazite_ore'},
		{INPUT: ORES.SMALL.IRIDIUM, 		OUTPUT: [{item : CRUSHED_ORES.IRIDIUM, 			count: 5}, {item : CRUSHED_ORES.IRIDIUM, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_iridium_ore'},
		{INPUT: ORES.SMALL.RUTILE, 			OUTPUT: [{item : CRUSHED_ORES.RUTILE, 			count: 5}, {item : CRUSHED_ORES.RUTILE, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_rutile_ore'},
		{INPUT: ORES.SMALL.STIBNITE, 		OUTPUT: [{item : CRUSHED_ORES.STIBNITE, 		count: 5}, {item : CRUSHED_ORES.STIBNITE, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_stibnite_ore'},
		{INPUT: ORES.SMALL.WOLFRAMITE, 		OUTPUT: [{item : CRUSHED_ORES.WOLFRAMITE, 		count: 5}, {item : CRUSHED_ORES.WOLFRAMITE, 	chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_wolframite_ore'},
		{INPUT: ORES.SMALL.CHROMITE, 		OUTPUT: [{item : CRUSHED_ORES.CHROMITE, 		count: 5}, {item : CRUSHED_ORES.CHROMITE, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_chromite_ore'},
		{INPUT: ORES.SMALL.URANINITE, 		OUTPUT: [{item : CRUSHED_ORES.URANIUM, 			count: 5}, {item : CRUSHED_ORES.URANIUM, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_uraninite_ore'},
		{INPUT: ORES.SMALL.PLATINUM, 		OUTPUT: [{item : CRUSHED_ORES.PLATINUM, 		count: 5}, {item : CRUSHED_ORES.PLATINUM, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_platinum_ore'},
		{INPUT: ORES.SMALL.OSMIUM, 			OUTPUT: [{item : CRUSHED_ORES.OSMIUM, 			count: 5}, {item : CRUSHED_ORES.OSMIUM, 		chance: 0.05 },{item: EXP, chance: 0.07 }], TIME: 400 , KEY: 'small_native_osmium_ore'},
	]
	recipes.forEach(recipe=>{
		event.custom({ 
			type: 'create:crushing',
			ingredients: [
				{ item:  recipe.INPUT}
			],
			results: recipe.OUTPUT,
			processingTime: recipe.TIME
		}).id(`create:crusshing/${recipe.KEY}`)
	})
})