onEvent('recipes', event => {
	const recipes=[
		{INPUT : ORES.NORMAL.ALUMINUM, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_aluminum'},
		{INPUT : ORES.NORMAL.LEAD, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_lead'},
		{INPUT : ORES.NORMAL.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_uranium'},
		{INPUT : ORES.NORMAL.BAUXITE, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_bauxite'},
		{INPUT : ORES.NORMAL.COPPER, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_copper'},
		{INPUT : ORES.NORMAL.MALACHITE, 	OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_malachite'},
		{INPUT : ORES.NORMAL.TETRAHEDRITE, 	OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_tetrahedrite'},
		{INPUT : ORES.NORMAL.GOLD, 			OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_gold'},
		{INPUT : ORES.NORMAL.MAGNETITE, 	OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_magnetite'},
		{INPUT : ORES.NORMAL.HEMATITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_hematite'},
		{INPUT : ORES.NORMAL.LIMONITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_limonite'},
		{INPUT : ORES.NORMAL.GALENA, 		OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_galena'},
		{INPUT : ORES.NORMAL.GARNIERITE, 	OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_garnierite'},
		{INPUT : ORES.NORMAL.SILVER, 		OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_silver'},
		{INPUT : ORES.NORMAL.CASSITERITE, 	OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_cassiterite'},
		{INPUT : ORES.NORMAL.SPHALERITE, 	OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_sphalerite'},
		{INPUT : ORES.NORMAL.BISMUTHINITE, 	OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_bismuthinite'},
		{INPUT : ORES.NORMAL.BERTRANDITE, 	OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_bertrandite'},
		{INPUT : ORES.NORMAL.COBALTITE, 	OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_cobaltite'},
		{INPUT : ORES.NORMAL.KERNITE, 		OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_kernite'},
		{INPUT : ORES.NORMAL.MONAZITE, 		OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_monazite'},
		{INPUT : ORES.NORMAL.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_iridium'},
		{INPUT : ORES.NORMAL.RUTILE, 		OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_rutile'},
		{INPUT : ORES.NORMAL.STIBNITE, 		OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_stibnite'},
		{INPUT : ORES.NORMAL.WOLFRAMITE, 	OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_wolframite'},
		{INPUT : ORES.NORMAL.CHROMITE, 		OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_chromite'},
		{INPUT : ORES.NORMAL.URANINITE, 	OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_uraninite'},
		{INPUT : ORES.NORMAL.PLATINUM, 		OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_platinum'},
		{INPUT : ORES.NORMAL.OSMIUM, 		OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.50, KEY: 'ore/normal_native_osmium'},
		
		{INPUT : ORES.POOR.ALUMINUM, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_aluminum'},
		{INPUT : ORES.POOR.LEAD, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_lead'},
		{INPUT : ORES.POOR.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_uranium'},
		{INPUT : ORES.POOR.BAUXITE, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_bauxite'},
		{INPUT : ORES.POOR.COPPER, 			OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_copper'},
		{INPUT : ORES.POOR.MALACHITE, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_malachite'},
		{INPUT : ORES.POOR.TETRAHEDRITE, 	OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_tetrahedrite'},
		{INPUT : ORES.POOR.GOLD, 			OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_gold'},
		{INPUT : ORES.POOR.MAGNETITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_magnetite'},
		{INPUT : ORES.POOR.HEMATITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_hematite'},
		{INPUT : ORES.POOR.LIMONITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_limonite'},
		{INPUT : ORES.POOR.GALENA, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_galena'},
		{INPUT : ORES.POOR.GARNIERITE, 		OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_garnierite'},
		{INPUT : ORES.POOR.SILVER, 			OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_silver'},
		{INPUT : ORES.POOR.CASSITERITE, 	OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_cassiterite'},
		{INPUT : ORES.POOR.SPHALERITE, 		OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_sphalerite'},
		{INPUT : ORES.POOR.BISMUTHINITE, 	OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_bismuthinite'},
		{INPUT : ORES.POOR.BERTRANDITE, 	OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_bertrandite'},
		{INPUT : ORES.POOR.COBALTITE, 		OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_cobaltite'},
		{INPUT : ORES.POOR.KERNITE, 		OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_kernite'},
		{INPUT : ORES.POOR.MONAZITE, 		OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_monazite'},
		{INPUT : ORES.POOR.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_iridium'},
		{INPUT : ORES.POOR.RUTILE, 			OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_rutile'},
		{INPUT : ORES.POOR.STIBNITE, 		OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_stibnite'},
		{INPUT : ORES.POOR.WOLFRAMITE, 		OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_wolframite'},
		{INPUT : ORES.POOR.CHROMITE, 		OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_chromite'},
		{INPUT : ORES.POOR.URANINITE, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_uraninite'},
		{INPUT : ORES.POOR.PLATINUM, 		OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_platinum'},
		{INPUT : ORES.POOR.OSMIUM, 			OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.25, KEY: 'ore/poor_native_osmium'},
		
		{INPUT : ORES.RICH.ALUMINUM, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_aluminum'},
		{INPUT : ORES.RICH.LEAD, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_lead'},
		{INPUT : ORES.RICH.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_uranium'},
		{INPUT : ORES.RICH.BAUXITE, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_bauxite'},
		{INPUT : ORES.RICH.COPPER, 			OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_copper'},
		{INPUT : ORES.RICH.MALACHITE, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_malachite'},
		{INPUT : ORES.RICH.TETRAHEDRITE, 	OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_tetrahedrite'},
		{INPUT : ORES.RICH.GOLD, 			OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_gold'},
		{INPUT : ORES.RICH.MAGNETITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_magnetite'},
		{INPUT : ORES.RICH.HEMATITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_hematite'},
		{INPUT : ORES.RICH.LIMONITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_limonite'},
		{INPUT : ORES.RICH.GALENA, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_galena'},
		{INPUT : ORES.RICH.GARNIERITE, 		OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_garnierite'},
		{INPUT : ORES.RICH.SILVER, 			OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_silver'},
		{INPUT : ORES.RICH.CASSITERITE, 	OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_cassiterite'},
		{INPUT : ORES.RICH.SPHALERITE, 		OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_sphalerite'},
		{INPUT : ORES.RICH.BISMUTHINITE, 	OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_bismuthinite'},
		{INPUT : ORES.RICH.BERTRANDITE, 	OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_bertrandite'},
		{INPUT : ORES.RICH.COBALTITE, 		OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_cobaltite'},
		{INPUT : ORES.RICH.KERNITE, 		OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_kernite'},
		{INPUT : ORES.RICH.MONAZITE, 		OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_monazite'},
		{INPUT : ORES.RICH.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_iridium'},
		{INPUT : ORES.RICH.RUTILE, 			OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_rutile'},
		{INPUT : ORES.RICH.STIBNITE, 		OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_stibnite'},
		{INPUT : ORES.RICH.WOLFRAMITE, 		OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_wolframite'},
		{INPUT : ORES.RICH.CHROMITE, 		OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_chromite'},
		{INPUT : ORES.RICH.URANINITE, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_uraninite'},
		{INPUT : ORES.RICH.PLATINUM, 		OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_platinum'},
		{INPUT : ORES.RICH.OSMIUM, 			OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'ore/rich_native_osmium'},
		
		{INPUT : ORES.SMALL.ALUMINUM, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_aluminum'},
		{INPUT : ORES.SMALL.LEAD, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_lead'},
		{INPUT : ORES.SMALL.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_uranium'},
		{INPUT : ORES.SMALL.BAUXITE, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_bauxite'},
		{INPUT : ORES.SMALL.COPPER, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_copper'},
		{INPUT : ORES.SMALL.MALACHITE, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_malachite'},
		{INPUT : ORES.SMALL.TETRAHEDRITE, 	OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_tetrahedrite'},
		{INPUT : ORES.SMALL.GOLD, 			OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_gold'},
		{INPUT : ORES.SMALL.MAGNETITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_magnetite'},
		{INPUT : ORES.SMALL.HEMATITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_hematite'},
		{INPUT : ORES.SMALL.LIMONITE, 		OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_limonite'},
		{INPUT : ORES.SMALL.GALENA, 		OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_galena'},
		{INPUT : ORES.SMALL.GARNIERITE, 	OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_garnierite'},
		{INPUT : ORES.SMALL.SILVER, 		OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_silver'},
		{INPUT : ORES.SMALL.CASSITERITE, 	OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_cassiterite'},
		{INPUT : ORES.SMALL.SPHALERITE, 	OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_sphalerite'},
		{INPUT : ORES.SMALL.BISMUTHINITE, 	OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_bismuthinite'},
		{INPUT : ORES.SMALL.BERTRANDITE, 	OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_bertrandite'},
		{INPUT : ORES.SMALL.COBALTITE, 		OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_cobaltite'},
		{INPUT : ORES.SMALL.KERNITE, 		OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_kernite'},
		{INPUT : ORES.SMALL.MONAZITE, 		OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_monazite'},
		{INPUT : ORES.SMALL.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_iridium'},
		{INPUT : ORES.SMALL.RUTILE, 		OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_rutile'},
		{INPUT : ORES.SMALL.STIBNITE, 		OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_stibnite'},
		{INPUT : ORES.SMALL.WOLFRAMITE, 	OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_wolframite'},
		{INPUT : ORES.SMALL.CHROMITE, 		OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_chromite'},
		{INPUT : ORES.SMALL.URANINITE, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_uraninite'},
		{INPUT : ORES.SMALL.PLATINUM, 		OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_platinum'},
		{INPUT : ORES.SMALL.OSMIUM, 		OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.10, KEY: 'ore/small_native_osmium'},
		
		{INPUT : CRUSHED_ORES.ALUMINUM, 	OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/aluminum_ore'},
		{INPUT : CRUSHED_ORES.COPPER, 		OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/copper_ore'},
		{INPUT : CRUSHED_ORES.GOLD, 		OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/gold_ore'},
		{INPUT : CRUSHED_ORES.WROUGHT_IRON, OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/wrought_iron_ore'},
		{INPUT : CRUSHED_ORES.LEAD, 		OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/lead_ore'},
		{INPUT : CRUSHED_ORES.NICKEL, 		OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/nickel_ore'},
		{INPUT : CRUSHED_ORES.SILVER, 		OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/silver_ore'},
		{INPUT : CRUSHED_ORES.TIN, 			OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/tin_ore'},
		{INPUT : CRUSHED_ORES.ZINC, 		OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/zinc_ore'},
		{INPUT : CRUSHED_ORES.BISMUTHINITE, OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/bismuthinite_ore'},
		{INPUT : CRUSHED_ORES.BERTRANDITE, 	OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/bertrandite_ore'},
		{INPUT : CRUSHED_ORES.COBALTITE, 	OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/cobaltite_ore'},
		{INPUT : CRUSHED_ORES.KERNITE, 		OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/kernite_ore'},
		{INPUT : CRUSHED_ORES.MONAZITE, 	OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/monazite_ore'},
		{INPUT : CRUSHED_ORES.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/iridium_ore'},
		{INPUT : CRUSHED_ORES.RUTILE, 		OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/rutile_ore'},
		{INPUT : CRUSHED_ORES.STIBNITE, 	OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/stibnite_ore'},
		{INPUT : CRUSHED_ORES.WOLFRAMITE, 	OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/wolframite_ore'},
		{INPUT : CRUSHED_ORES.CHROMITE, 	OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/chromite_ore'},
		{INPUT : CRUSHED_ORES.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/uranium_ore'},
		{INPUT : CRUSHED_ORES.PLATINUM, 	OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/platinum_ore'},
		{INPUT : CRUSHED_ORES.OSMIUM, 		OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'crushed/osmium_ore'},
		
		{INPUT : DUSTS.ALUMINUM, 		OUTPUT : {item : NUGGETS.ALUMINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/aluminum'},
		{INPUT : DUSTS.COPPER, 			OUTPUT : {item : NUGGETS.COPPER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/copper'},
		{INPUT : DUSTS.GOLD, 			OUTPUT : {item : NUGGETS.GOLD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/gold'},
		{INPUT : DUSTS.WROUGHT_IRON, 	OUTPUT : {item : NUGGETS.WROUGHT_IRON, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/wrought_iron'},
		{INPUT : DUSTS.LEAD, 			OUTPUT : {item : NUGGETS.LEAD, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/lead'},
		{INPUT : DUSTS.NICKEL, 			OUTPUT : {item : NUGGETS.NICKEL, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/nickel'},
		{INPUT : DUSTS.SILVER, 			OUTPUT : {item : NUGGETS.SILVER, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/silver'},
		{INPUT : DUSTS.TIN, 			OUTPUT : {item : NUGGETS.TIN, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/tin'},
		{INPUT : DUSTS.ZINC, 			OUTPUT : {item : NUGGETS.ZINC, 			count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/zinc'},
		{INPUT : DUSTS.BISMUTH, 		OUTPUT : {item : NUGGETS.BISMUTH, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/bismuth'},
		{INPUT : DUSTS.BERYLLIUM, 		OUTPUT : {item : NUGGETS.BERYLLIUM, 	count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/beryllium'},
		{INPUT : DUSTS.COBALT, 			OUTPUT : {item : NUGGETS.COBALT, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/cobalt'},
		{INPUT : DUSTS.BORON, 			OUTPUT : {item : NUGGETS.BORON, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/boron'},
		{INPUT : DUSTS.THORIUM, 		OUTPUT : {item : NUGGETS.THORIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/thorium'},
		{INPUT : DUSTS.IRIDIUM, 		OUTPUT : {item : NUGGETS.IRIDIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/iridium'},
		{INPUT : DUSTS.TITANIUM, 		OUTPUT : {item : NUGGETS.TITANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/titanium'},
		{INPUT : DUSTS.ANTIMONY, 		OUTPUT : {item : NUGGETS.ANTIMONY, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/antimony'},
		{INPUT : DUSTS.TUNGSTEN, 		OUTPUT : {item : NUGGETS.TUNGSTEN, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/tungsten'},
		{INPUT : DUSTS.CHROMIUM, 		OUTPUT : {item : NUGGETS.CHROMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/chromium'},
		{INPUT : DUSTS.URANIUM, 		OUTPUT : {item : NUGGETS.URANIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/uranium'},
		{INPUT : DUSTS.PLATINUM, 		OUTPUT : {item : NUGGETS.PLATINUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/platinum'},
		{INPUT : DUSTS.OSMIUM, 			OUTPUT : {item : NUGGETS.OSMIUM, 		count: 1 }, TIME : 100, EXP: 0.75, KEY: 'dust/osmium'}
	]
	recipes.forEach(recipe=>{
		event.custom({
			type: RECIPE_TYPE.MC_BLASTING,
			ingredient: { 
				item: recipe.INPUT 
			},
			result: recipe.OUTPUT,
			cookingtime: recipe.TIME,
			experience: recipe.EXP
		}).id(`minecraft:blasting/${recipe.KEY}`)
	})
})