onEvent('recipes', event => {
	const recipes=[
		{BASE: CREATE_ITEMS.ANDESITE_MACHINE, 	ADDITION: BLOCKS.TITANIUM, 						RESULT: CREATE_ITEMS.PRESS, 					KEY: 'create/mechanical_press'},
		{BASE: CREATE_ITEMS.ANDESITE_MACHINE, 	ADDITION: CREATE_ITEMS.WHISK, 					RESULT: CREATE_ITEMS.MIXER, 					KEY: 'create/mechanical_mixer'},
		{BASE: CREATE_ITEMS.ANDESITE_MACHINE, 	ADDITION: IE_ITEM.ROCKCUTTER, 					RESULT: CREATE_ITEMS.SAW, 						KEY: 'create/mechanical_saw'},
		{BASE: CREATE_ITEMS.ANDESITE_MACHINE, 	ADDITION: CREATE_ITEMS.FLUID_TANK, 				RESULT: CREATE_ITEMS.SPOUT, 					KEY: 'create/spout'},
		{BASE: CREATE_ITEMS.BRASS_CASING, 		ADDITION: CREATE_ITEMS.FLUID_TANK, 				RESULT: CREATE_ITEMS.DRAIN,						KEY: 'create/item_drain'},
		{BASE: CREATE_ITEMS.BRASS_MACHINE, 		ADDITION: CREATE_ITEMS.BRASS_HAND, 				RESULT: CREATE_ITEMS.DEPLOYER, 					KEY: 'create/deployer'},
		{BASE: TC_ITEM.SEARED_MELTER, 			ADDITION: CREATE_ITEMS.MIXER, 					RESULT: TC_ITEM.SCORCHED_ALLOYER, 				KEY: 'tconstruct/scorched_alloyer'},
		{BASE: CREATE_ITEMS.MECHANICAL_CRAFTER,	ADDITION: IE_ITEM.ROCKCUTTER, 					RESULT: MC_ITEM.STONECUTTER, 					KEY: 'minecraft/stonecutter'},
		{BASE: CREATE_ITEMS.BRASS_MACHINE, 		ADDITION: CREATE_ITEMS.PRECISION_MECHANISM, 	RESULT: CREATE_ITEMS.ROTATION_SPEED_CONTROLLER,	KEY: 'create/rotation_speed_controller'},
		{BASE: CREATE_ITEMS.FLUID_PIPER, 		ADDITION: GREATE_PLATES.SOLDER,					RESULT: CREATE_ITEMS.FLUID_VALVE,				KEY: 'create/fluid_valve'},
		{BASE: CREATE_ITEMS.FLUID_VALVE, 		ADDITION: CREATE_ITEMS.ELECTRON_TUBE,			RESULT: CREATE_ITEMS.SMART_FLUID_PIPE,			KEY: 'create/smart_fluid_pipe'},
		{BASE: CREATE_ITEMS.ANDESITE_ALLOY, 	ADDITION: `#${TAGS.TFC_LUMBER}`,				RESULT: CREATE_ITEMS.PISTON_EXTENSION_POLE,		KEY: 'create/piston_extension_pole'},
		{BASE: MC_ITEM.PISTONE, 				ADDITION: CREATE_ITEMS.PISTON_EXTENSION_POLE,	RESULT: CREATE_ITEMS.MECHANICAL_PISTON,			KEY: 'create/mechanical_piston'},
		{BASE: CREATE_ITEMS.ANDESITE_CASING, 	ADDITION: MC_ITEM.SLIME_BALL,					RESULT: CREATE_ITEMS.WINDMILL_BEARING,			KEY: 'create/windmill_bearing'},
		{BASE: CREATE_ITEMS.WINDMILL_BEARING, 	ADDITION: CREATE_ITEMS.COGWHEEL,				RESULT: CREATE_ITEMS.GANTRY_CARRIAGE,			KEY: 'create/gantry_carriage'},
		{BASE: CREATE_ITEMS.WINDMILL_BEARING, 	ADDITION: CREATE_ITEMS.SHAFT,					RESULT: CREATE_ITEMS.MECHANICAL_BEARING,		KEY: 'create/mechanical_bearing'},
		{BASE: CREATE_ITEMS.MECHANICAL_BEARING, ADDITION: CREATE_ITEMS.ELECTRON_TUBE,			RESULT: CREATE_ITEMS.CLOCKWORK_BEARING,			KEY: 'create/clockwork_bearing'},
		{BASE: CREATE_ITEMS.BRASS_MACHINE,		ADDITION: MC_ITEM.CLOCK,						RESULT: CREATE_ITEMS.CUCKOO_CLOCK,				KEY: 'create/cuckoo_clock'},
		{BASE: CREATE_ITEMS.BRASS_MACHINE,		ADDITION: CREATE_ITEMS.COPPER_MACHINE,			RESULT: CREATE_ITEMS.STEAM_ENGINE,				KEY: 'create/steam_engine'},
		{BASE: CREATE_ITEMS.ELECTRON_TUBE,		ADDITION: CREATE_ITEMS.ELECTRON_TUBE,			RESULT: CREATE_ITEMS.NIXIE_TUBE,				KEY: 'create/nixie_tube'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: `#${TAGS.M_WOODEN_TRAPDOORS}`,		RESULT: CREATE_ITEMS.TRAIN_TRAPDOOR,			KEY: 'create/train_trapdoor'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: `#${TAGS.M_WOODEN_DOORS}`,			RESULT: CREATE_ITEMS.TRAIN_DOOR,				KEY: 'create/train_door'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: CREATE_ITEMS.PRECISION_MECHANISM,		RESULT: CREATE_ITEMS.CONTROLS,					KEY: 'create/controls'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: `#${TAGS.M_WOODEN_PRESSURE_PLATES}`,	RESULT: CREATE_ITEMS.TRACK_OBSERVER,			KEY: 'create/track_observer'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: CREATE_ITEMS.ELECTRON_TUBE,			RESULT: CREATE_ITEMS.TRACK_SIGNAL,				KEY: 'create/track_signal'},
		{BASE: CREATE_ITEMS.RAILWAY_CASING,		ADDITION: MC_ITEM.COMPASS,						RESULT: CREATE_ITEMS.TRACK_STATION,				KEY: 'create/track_station'},
		{BASE: CREATE_ITEMS.ANDESITE_CASING,	ADDITION: `#${TAGS.M_WOODEN_DOORS}`,			RESULT: CREATE_ITEMS.ANDESITE_DOOR,				KEY: 'create/andesite_door'},
		{BASE: CREATE_ITEMS.COPPER_CASING,		ADDITION: `#${TAGS.M_WOODEN_DOORS}`,			RESULT: CREATE_ITEMS.COPPER_DOOR,				KEY: 'create/copper_door'},
		{BASE: CREATE_ITEMS.BRASS_CASING,		ADDITION: `#${TAGS.M_WOODEN_DOORS}`,			RESULT: CREATE_ITEMS.BRASS_DOOR,				KEY: 'create/brass_door'},
		{BASE: CREATE_ITEMS.BRASS_CASING,		ADDITION: MC_ITEM.REDSTONE_TORCH,				RESULT: CREATE_ITEMS.REDSTONE_LINK,				KEY: 'create/redstone_link'},
		{BASE: CREATE_ITEMS.ANDESITE_CASING,	ADDITION: IE_ITEM.STICK,						RESULT: CREATE_ITEMS.ANALOG_LEVER,				KEY: 'create/analog_lever'},
		{BASE: CREATE_ITEMS.MECHANICAL_DRILL,	ADDITION: CREATE_ITEMS.CRUSHING_WHEEL,			RESULT: CREATE_ITEMS.MECHANICAL_ROLLER,			KEY: 'create/mechanical_roller'}
	]

	
	recipes.forEach(recipe=>{
		event.remove({output : recipe.RESULT})
		event.custom({
			type: RECIPE_TYPE.MC_SMITHING,
			base: { 
				item: recipe.BASE 
			},
			addition: Id_or_tag_to_item(recipe.ADDITION),
			result: { 
				item: recipe.RESULT 
			}
		}).id(`minecraft:smithing/${recipe.KEY}`)
	})
})